spring.application.name=ebanking-backend

# ==============================
# H2 In-Memory Database (dev)
# ==============================
spring.datasource.url=jdbc:h2:mem:ebank-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==============================
# JPA / Hibernate
# ==============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================
# Server
# ==============================
server.port=8085

# ==============================
# Springdoc / Swagger UI
# ==============================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
